# Generated by Django 4.0 on 2022-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='Kutsuvieras'),
        ),
    ]
