# Generated by Django 4.0 on 2022-07-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_participant_is_vege_participant_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='dont_show_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='show_name',
            field=models.BooleanField(default=True, verbose_name='Nimi saa näkyä listalla'),
        ),
    ]
