# Generated by Django 4.0 on 2022-07-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_participant_dont_show_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='starting_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Opintojen aloitusvuosi'),
        ),
    ]
